[package]
name = "chipioindustries/get-user-id"
description = "Simple function for getting a user ID as a string, or the local player's user ID if called from the client."
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["wally.exe", "aftman", "*.zip"]

[dependencies]
t = "osyrisrblx/t@3.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"